### PR TITLE
Expose access token

### PR DESCRIPTION
**Pull request by igorw**

### CODE REVIEW

**Comment by RISCfuture** [comment]
Before I pull, I'd just like to know why?  What's the motivation for exposing the access token?

**Comment by igorw** [comment]
Sure. :)

When you have another app that needs to use the keys, there is currently no way to fetch them through this library (correct me if I'm wrong). By exposing the access_token method you can get access token/secret and pass them to your other app.

**Comment by igorw** [comment]
Bumping this.

**Comment by RISCfuture** [comment]
Done, sorry.

**Comment by igorw** [comment]
Great, thanks!

**Comment by alphatester** [comment]
How to reuse the access_token? I'm saving it in my db and then try to reuse it that way
  dropbox_session = Dropbox::Session.new('myappkey', 'myappsecret')
  dropbox_session.authorize(:access_token =>{ :token =>' userkey' ,:secret_token => 'usersecret'})
but I got a 403 error

**Comment by RISCfuture** [comment]
You should use the `Dropbox::Session#set_access_token` method to specify a custom access token and secret that you obtained from elsewhere.

**Pull request merged**
